version: "3.9"

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - services

  backend:
    build:
      context: ../
      dockerfile: ./backend/Dockerfile
    env_file: .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_volum:/app/media
      - static_volum:/app/static
    networks:
      - services

  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volum:/var/html/static/
      - media_volum:/var/html/media/
    depends_on:
      - backend
    networks:
      - services


volumes:
  db_data:
  static_volum:
  media_volum:

networks:
  services:
    name: store
