# Generated by Django 5.0.6 on 2024-06-16 10:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории', max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Используйте slug состаящий из латинских букв, цифр и символа _', unique=True, validators=[django.core.validators.RegexValidator(message='Используйте slug состаящий из латинских букв, цифр и символа _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг')),
                ('image', models.ImageField(db_comment='Изображение категории', help_text='Выберете изображение категории', upload_to='categories/', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table_comment': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Название', help_text='Введите название продукта', max_length=200, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(db_comment='Цена', decimal_places=2, error_messages={'min_value': 'Минимальная цена должна быть больше или равна 0'}, help_text='Введите цену продукта', max_digits=13, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('slug', models.SlugField(help_text='Используйте slug состаящий из латинских букв, цифр и символа _', unique=True, validators=[django.core.validators.RegexValidator(message='Используйте slug состаящий из латинских букв, цифр и символа _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг')),
                ('original_image', models.ImageField(db_comment='Оригинальное изображение продукта', help_text='Выберете оригинальное изображение продукта', upload_to='products/', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table_comment': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(db_comment='Количество продуктов', error_messages={'min_value': 'Минимальное количество продуктов должно быть больше или равно 1'}, help_text='Выберите количество продуктов, добавленных в корзину.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количесво продуктов')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_comment='Дата добавления', help_text='Дата и время добавления товара в корзину.', verbose_name='Дата добавления')),
                ('product', models.ForeignKey(help_text='Выберите продукт, добавленный в корзину.', on_delete=django.db.models.deletion.CASCADE, related_name='shoping_cart', to='store.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(db_comment='Пользователь', help_text='Выберите пользователя, добавившего продукт в корзину.', on_delete=django.db.models.deletion.CASCADE, related_name='shoping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина с продуктами',
                'verbose_name_plural': 'Корзины с продуктами',
                'db_table_comment': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории', max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Используйте slug состаящий из латинских букв, цифр и символа _', unique=True, validators=[django.core.validators.RegexValidator(message='Используйте slug состаящий из латинских букв, цифр и символа _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг')),
                ('image', models.ImageField(db_comment='Изображение подкатегории', help_text='Выберете изображение подкатегории', upload_to='subcategories/', verbose_name='Подкатегория')),
                ('category', models.ForeignKey(db_comment='Категория', help_text='Введите родительскую категорию', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table_comment': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(db_comment='Подкатегория продукта', help_text='Выберете подкатегорию продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subcategory', verbose_name='Подкатегория продукта'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_shoping_card'),
        ),
    ]
