# Generated by Django 5.0.6 on 2024-06-19 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='count',
            field=models.PositiveIntegerField(db_comment='Количество продуктов', default=1, error_messages={'min_value': 'Минимальное количество продуктов должно быть больше или равно 1'}, help_text='Выберите количество продуктов, добавленных в корзину.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количесво продуктов'),
        ),
    ]
